import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./calendar.css";
import { SocketProvider } from "../SocketProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
        <SocketProvider>
            {children}
        </SocketProvider>
        </>
    );
}
